version: 2.0.0.{build}

os: Windows Server 2012

test: off
 
build_script:
 - .\BuildScripts\_main.bat -nopause

assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "2.0.0-preview0{build}"

artifacts:
  - path: bin\NuGetPackages\*.nupkg

nuget:
  account_feed: true
  project_feed: true


deploy:
  provider: NuGet
  # server: https://staging.nuget.org
  api_key: JPBrgilXGK52uuHgtpM8XDNO6C7RYfYRef6hfadvyVQh/mBKDBhdTw+2tWoA+gXg
    secure: 
  skip_symbols: true # skip symbols for preview packages
  artifact: /.*\.nupkg/