version: 2.0.0.{build}
os: Visual Studio 2015
test: off

build_script:
  - .\BuildScripts\_main.bat -nopause

skip_commits:
  message: /skip build.*/

assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "2.0.0"
  assembly_file_version: "2.0.0"
  assembly_informational_version: "2.0.0"