version: 2.0.0.{build}
os: Windows Server 2012
test: off

environment:
  CODECOV_TOKEN:
    secure: 5KhRL8Us1o7f3qgvMWYjmYUaaayFBMBkSn1YHs93wvzPrbx+2YpooScYIR14o/Q9

install:
  - choco install git --params="/GitAndUnixToolsOnPath"

build_script:
  - .\BuildScripts\_main.bat -nopause

on_success:
  - bash <(curl https://codecov.io/bash) 

assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "2.0.0-rc3build{build}"

artifacts:
  - path: bin\NuGetPackages\*.nupkg

nuget:
  account_feed: true
  project_feed: true

deploy:
  provider: NuGet
  # server: https://staging.nuget.org
  api_key: 
    secure: JPBrgilXGK52uuHgtpM8XDNO6C7RYfYRef6hfadvyVQh/mBKDBhdTw+2tWoA+gXg 
  skip_symbols: true # skip symbols for preview packages
  artifact: /.*\.nupkg/