version: 2.0.0.{build}
os: Windows Server 2012
test: off

environment:
  COVERALLS_REPO_TOKEN:
    secure: wbdO3ggQGIggpCZU0oZiL2C6rQKf+ksiGllDbLD46fpC2eLyqnsmv4+LnG0bWVYA

assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "2.0.0-rc2build{build}"

artifacts:
  - path: bin\NuGetPackages\*.nupkg

build_script:
  - .\BuildScripts\_main.bat -nopause

on_success:
  - ps: >-
        Write-Host $env:APPVEYOR_REPO_BRANCH
        .\packages\coveralls.net.0.5.0\csmacnz.Coveralls.exe --opencover -i ./bin/Reports/Coverage.xml --repoToken $env:COVERALLS_REPO_TOKEN

nuget:
  account_feed: true
  project_feed: true

deploy:
  provider: NuGet
  # server: https://staging.nuget.org
  api_key: 
    secure: JPBrgilXGK52uuHgtpM8XDNO6C7RYfYRef6hfadvyVQh/mBKDBhdTw+2tWoA+gXg 
  skip_symbols: true # skip symbols for preview packages
  artifact: /.*\.nupkg/