image:
  - Visual Studio 2019
  - Ubuntu
  - macOS

version: 5.0.0-preview-1-build-{build}

test: off

skip_commits:
  message: /skipci .*/

build_script:
  - dotnet build -f netstandard2.0 -c:Release -v:m -p:DevMode=false
  - dotnet test --no-build -f netcoreapp3.1 -c:Release -p:DevMode=false

for:
  - matrix:
      only:
        - image: Visual Studio 2019

    build_script:
      - dotnet build -c:Release -v:m -p:DevMode=false
      - dotnet test --no-build -c:Release -p:DevMode=false

    artifacts:
      - path: .\.dist\packages\*.nupkg
