version: 3.0.0.{build}
os: Visual Studio 2017
test: off

build_script:
  - .\BuildScripts\_main.bat -MSB15 -nopause

skip_commits:
  message: /skip .*/

artifacts:
  - path: bin\NuGetPackages\*.nupkg