version: 2.0.0.{build}
os: Windows Server 2012
test: off

install:
 - pip install codecov
 
build_script:
 - .\BuildScripts\_main.bat -nopause

after_build:
 - codecov --token=010207f8-6304-48b3-a71d-e9437ca26b76 

assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "2.0.0-rc1build{build}"

artifacts:
  - path: bin\NuGetPackages\*.nupkg

nuget:
  account_feed: true
  project_feed: true


deploy:
  provider: NuGet
  # server: https://staging.nuget.org
  api_key: 
    secure: JPBrgilXGK52uuHgtpM8XDNO6C7RYfYRef6hfadvyVQh/mBKDBhdTw+2tWoA+gXg 
  skip_symbols: true # skip symbols for preview packages
  artifact: /.*\.nupkg/