version: 2.0.0
os: Windows Server 2012
test: off

build_script:
  - .\BuildScripts\_main.bat -nopause

assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"