version: 5.0.0-preview-1-{build}

image:
  - Visual Studio 2019
  - Ubuntu
  - macOS

test: off

build_script:
  - dotnet build -c:Release -v:m -p:DevMode=false & dotnet test --no-build -c:Release -p:DevMode=false

skip_commits:
  message: /skipci .*/

artifacts:
  - path: .\.dist\packages\*.nupkg
