image:
  - Visual Studio 2019
  - Ubuntu
  - macOS

version: 5.0.0-preview-1-build-{build}

test: off

skip_commits:
  message: /skipci .*/

build_script:
  - dotnet test -f netcoreapp3.1 -c:Release test/DryIoc.UnitTests/DryIoc.UnitTests.csproj
  - dotnet test -f netcoreapp3.1 -c:Release test/DryIoc.IssuesTests/DryIoc.IssuesTests.csproj
  - dotnet test -f netcoreapp3.1 -c:Release test/DryIoc.CommonServiceLocator.UnitTests/DryIoc.CommonServiceLocator.UnitTests.csproj
  - dotnet test -f netcoreapp3.1 -c:Release test/DryIoc.Microsoft.DependencyInjection.Specification.Tests/DryIoc.Microsoft.DependencyInjection.Specification.Tests.csproj

for:
  - matrix:
      only:
        - image: Visual Studio 2019

    build_script:
      - dotnet build -c:Release -v:m -p:DevMode=false
      - dotnet test --no-build -c:Release -p:DevMode=false

    artifacts:
      - path: .\.dist\packages\*.nupkg
